# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs/docs-test/1.0.0/
          cname: ""
      
      # Print the GitHub Pages URL
      - name: Get Pages URL
        run: |
          echo "GitHub Pages URL: https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}"
      
      # Output the GitHub Pages URL as a job output
      - name: Set output
        id: output_url
        run: echo "::set-output name=pages_url::https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}"
      
